# Generated by Django 5.1.5 on 2025-03-07 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_tourist_spot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tourist_spot',
            new_name='TouristSpot',
        ),
        migrations.CreateModel(
            name='TouristSpotKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.keyword')),
                ('tourist_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.touristspot')),
            ],
            options={
                'unique_together': {('tourist_spot', 'keyword')},
            },
        ),
    ]
