# Generated by Django 5.1.5 on 2025-03-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_remove_touristspot_picture_url_touristspot_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='workingday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
