# Generated by Django 5.1.5 on 2025-03-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0011_alter_touristspot_prefecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='picture',
            field=models.ImageField(default='images/default_picture.jpg', upload_to='tourist_spot_images/'),
            preserve_default=False,
        ),
    ]
