# Generated by Django 5.1.5 on 2025-03-12 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_touristspot_price_average_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_score', models.IntegerField()),
                ('review_title', models.CharField(max_length=50)),
                ('review_description', models.TextField()),
                ('review_price', models.IntegerField(choices=[(1, '0～1,000円'), (2, '1,000～2,000円'), (3, '2,000～3,000円'), (4, '3,000～4,000円'), (5, '4,000～5,000円'), (6, '5,000～6,000円'), (7, '6,000～7,000円'), (8, '7,000～8,000円'), (9, '8,000～9,000円'), (10, '9,000～10,000円'), (11, '10,000～20,000円'), (12, '20,000～30,000円'), (13, '30,000～40,000円'), (14, '40,000～50,000円'), (15, '50,000～60,000円'), (16, '60,000～70,000円'), (17, '70,000～80,000円'), (18, '80,000～90,000円'), (19, '90,000～100,000円'), (20, '100,000円以上')])),
                ('stay_time_min', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tourist_spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelapp.touristspot')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
