# Generated by Django 5.1.5 on 2025-03-13 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0014_userreview_wantedspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedspot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wanted_spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
