# Generated by Django 5.1.5 on 2025-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_alter_touristplan_spot_tourist_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplan_spot',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
