# Generated by Django 5.1.5 on 2025-04-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_touristplan_spot_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='price_average',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='review_score_average',
        ),
        migrations.RemoveField(
            model_name='touristspot',
            name='staytime_average',
        ),
    ]
