# Generated by Django 5.1.5 on 2025-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0019_remove_touristspot_price_average_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='category',
            field=models.IntegerField(choices=[(1, '神社/仏閣/歴史的建造物'), (2, 'アクティビティ'), (3, 'テーマパーク'), (4, '景勝'), (5, '博物館/美術館'), (6, '動物園/水族館'), (7, '温泉/スパ'), (8, 'ビーチ/海水浴場'), (9, '登山/ハイキング'), (10, 'ショッピングモール'), (11, 'カフェ/レストラン'), (12, '農場/園芸'), (13, '映画館/劇場'), (14, 'その他')]),
        ),
    ]
