# Generated by Django 5.1.5 on 2025-04-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0020_alter_touristspot_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
